#!/bin/sh
cd "${0%/*}" || exit                            # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions    # Tutorial run functions
#------------------------------------------------------------------------------

# Restore initial fields
restore0Dir

<<<APPLICATIONS>>>

runApplication $(getApplication)

