#!/bin/sh
cd "${0%/*}" || exit                            # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions    # Tutorial run functions
#------------------------------------------------------------------------------

# Restore initial fields (prior to decompose)
restore0Dir

<<<APPLICATIONS>>>

# runApplication decomposePar

mpirun -np 20 redistributePar -decompose -parallel

runParallel $(getApplication)

# mpirun -np 20 redistributePar -reconstruct -parallel

#------------------------------------------------------------------------------
